name: Deploy website

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v1
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: ls